drop table hub;
CREATE TABLE Hub (
     codHub varchar(5) NOT NULL,
     tipoHub VARCHAR(50) NOT NULL,
     lat number,
     lng number,
     constraint pk_codHub PRIMARY KEY (codHub)
);

drop table Clientes;
create table Clientes (
    codInterno integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
    tipo varchar(1) constraint nnTipoCliente NOT NULL,
    nome varchar(100) constraint nnNomeCliente NOT NULL,
    emailCliente varchar(255) constraint unEmailCliente UNIQUE,
    plafond float constraint nnPlafondCliente NOT NULL,
    nrFiscal integer constraint unNrFiscalCliente UNIQUE,
    constraint pk_CodInterno PRIMARY KEY (codInterno)
);
alter table Clientes add CONSTRAINT ckemailvalidation CHECK ( REGEXP_LIKE ( emailCliente, '^[A-Za-z]+[A-Za-z0-9.]+@[A-Za-z0-9.-]+.[A-Za-z]{2,4}$' ) );
alter table Clientes add constraint ckTipoCliente CHECK(tipo='P' OR tipo='E');
alter table Clientes add constraint ck_nrFiscal CHECK(REGEXP_LIKE(nrFiscal,'^[0-9]{9}$'));

drop table hubCliente;
Create table hubCliente(
    codHub varchar(5) not null,
    codInterno int,
    constraint pk_CodInterno PRIMARY KEY(codInterno)
);
alter table hubCliente add constraint fk_hubCliente_codInterno FOREIGN KEY  (codInterno) references Cliente(codInterno);
alter table hubCliente add constraint fk_hubCliente_codHub FOREIGN KEY  (codInterno) references Hub(codHub);


drop table input_hub;
CREATE TABLE input_hub(
    input_string VARCHAR(25),
    constraint pkInput_hub primary key (input_string)
);