CREATE OR REPLACE Procedure registerOperation(tipoOperacao Operacoes.tipo%type,formaAplicacao Operacoes.formaAplicacao%type,produto Operacoes.codproduto%type,quantidade Operacoes.quantidade%type,dataRealizacao Operacoes.dataOperacao%type)
AS
invalidOperation Exception;
BEGIN
insert into Operacoes(tipoOperacao,formaAplicacao,produto,quantidade,dataRealizacao) Values (tipoOperacao,formaAplicacao,produto,quantidade,dataRealizacao);
Exception
when invalidOperation then
RAISE_APPLICATION_ERROR(-20001,'Invalid Operation Parameters');
END;

codOperacao integer GENERATED BY DEFAULT ON NULL AS IDENTITY,
anoPlanoAnual integer,
codCalendarioOperacoes integer,
dataPrevistaPlano date constraint nnDataPrevistaPlano NOT NULL,
dataOperacao date constraint nnDataOperacao NOT NULL,
tipoOperacao varchar(2) constraint nnTipoOperacao NOT NULL,
formaAplicacao varchar(2) constraint nnFormaAplicacao NOT NULL,
estadoOperacao